version: '3'

networks:
  default:
    external:
      name: float-network

services:
  nginx-hello:
    image: floatapp/nginx-hello:latest
    networks:
      - float-network
    ports:
      - "8080:80"
