version: '3'

networks:
  float-network:
    driver: overlay

services:
  nginx-hello:
    image: floatapp/nginx-hello:${CF_SHORT_REVISION}
    networks:
      - float-network
    ports:
      - "8080:80"
